"""
Database models for incident management.

Defines the structure for Incidents, Alert payloads, and synthesized
RootCauseReports in the PostgreSQL/SQLite database using SQLAlchemy 2.0 style.
"""

from datetime import datetime, timezone
import uuid
from typing import Any, Optional

from sqlalchemy import Float, ForeignKey, JSON, String
from sqlalchemy.orm import Mapped, mapped_column, relationship

from ..core.database import Base
from ..enums import IncidentStatus


def generate_uuid() -> str:
    """Generate a standard UUID string."""
    return str(uuid.uuid4())


def utc_now_naive() -> datetime:
    """Generate a timezone-naive datetime representing UTC.

    This matches SQLite and PostgreSQL defaults without timezone conversion issues.
    """
    return datetime.now(timezone.utc).replace(tzinfo=None)


class Incident(Base):
    """Represents a unique service incident undergoing investigation."""

    __tablename__ = "incidents"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=generate_uuid)
    service_id: Mapped[str] = mapped_column(String(100), nullable=False, index=True)
    status: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        default=IncidentStatus.INVESTIGATING,
    )
    created_at: Mapped[datetime] = mapped_column(default=utc_now_naive, nullable=False)
    updated_at: Mapped[datetime] = mapped_column(
        default=utc_now_naive,
        onupdate=utc_now_naive,
        nullable=False,
    )

    # Relationships
    alerts: Mapped[list["Alert"]] = relationship(
        "Alert",
        back_populates="incident",
        cascade="all, delete-orphan",
        lazy="selectin",
    )
    report: Mapped[Optional["RootCauseReportModel"]] = relationship(
        "RootCauseReportModel",
        back_populates="incident",
        uselist=False,
        cascade="all, delete-orphan",
        lazy="selectin",
    )
    resolution: Mapped[Optional["IncidentResolution"]] = relationship(
        "IncidentResolution",
        back_populates="incident",
        uselist=False,
        cascade="all, delete-orphan",
        lazy="selectin",
    )

    def to_dict(self) -> dict[str, Any]:
        """Convert model representation to a dictionary."""
        return {
            "id": self.id,
            "service_id": self.service_id,
            "status": self.status,
            "created_at": self.created_at.isoformat(),
            "updated_at": self.updated_at.isoformat(),
            "alerts": [alert.to_dict() for alert in self.alerts],
            "report": self.report.to_dict() if self.report else None,
            "resolution": self.resolution.to_dict() if self.resolution else None,
        }


class Alert(Base):
    """Represents an individual alert payload received via ingestion."""

    __tablename__ = "alerts"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=generate_uuid)
    incident_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("incidents.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    alert_message: Mapped[str] = mapped_column(String(1000), nullable=False)
    created_at: Mapped[datetime] = mapped_column(default=utc_now_naive, nullable=False)

    # Relationships
    incident: Mapped["Incident"] = relationship("Incident", back_populates="alerts")

    def to_dict(self) -> dict[str, Any]:
        """Convert alert fields to a dictionary."""
        return {
            "id": self.id,
            "incident_id": self.incident_id,
            "alert_message": self.alert_message,
            "created_at": self.created_at.isoformat(),
        }


class RootCauseReportModel(Base):
    """Represents a persisted RootCauseReport generated by the orchestrator."""

    __tablename__ = "root_cause_reports"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=generate_uuid)
    incident_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("incidents.id", ondelete="CASCADE"),
        unique=True,
        nullable=False,
        index=True,
    )
    root_cause: Mapped[str] = mapped_column(String(2000), nullable=False)
    affected_services: Mapped[list[str]] = mapped_column(JSON, nullable=False)
    raw_logs: Mapped[dict] = mapped_column(JSON, nullable=False, default=dict)
    raw_metrics: Mapped[dict] = mapped_column(JSON, nullable=False, default=dict)
    observability_analysis: Mapped[str] = mapped_column(String(4000), nullable=False, default="")
    code_diffs: Mapped[dict] = mapped_column(JSON, nullable=False, default=dict)
    past_resolutions: Mapped[list] = mapped_column(JSON, nullable=False, default=list)
    remediation_steps: Mapped[list[str]] = mapped_column(JSON, nullable=False)
    confidence_score: Mapped[float] = mapped_column(Float, nullable=False)
    uncertainty: Mapped[str] = mapped_column(String(2000), nullable=False, default="")
    created_at: Mapped[datetime] = mapped_column(default=utc_now_naive, nullable=False)

    # Relationships
    incident: Mapped["Incident"] = relationship("Incident", back_populates="report")

    def to_dict(self) -> dict[str, Any]:
        """Convert report fields to a dictionary."""
        return {
            "id": self.id,
            "incident_id": self.incident_id,
            "root_cause": self.root_cause,
            "affected_services": self.affected_services,
            "raw_logs": self.raw_logs,
            "raw_metrics": self.raw_metrics,
            "observability_analysis": self.observability_analysis,
            "code_diffs": self.code_diffs,
            "past_resolutions": self.past_resolutions,
            "remediation_steps": self.remediation_steps,
            "confidence_score": self.confidence_score,
            "uncertainty": self.uncertainty,
            "created_at": self.created_at.isoformat(),
        }

