"""
Database models for incident management.

Defines the structure for Incidents, Alert payloads, and synthesized
RootCauseReports in the PostgreSQL/SQLite database.
"""

from datetime import datetime
import uuid
from typing import Any

from sqlalchemy import Column, DateTime, Float, ForeignKey, JSON, String
from sqlalchemy.orm import relationship

from ..core.database import Base


def generate_uuid() -> str:
    """Generate a standard UUID string."""
    return str(uuid.uuid4())


class Incident(Base):
    """Represents a unique service incident undergoing investigation."""

    __tablename__ = "incidents"

    id = Column(String(36), primary_key=True, default=generate_uuid)
    service_id = Column(String(100), nullable=False, index=True)
    status = Column(String(50), nullable=False, default="investigating")  # investigating, completed, failed
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)

    # Relationships
    alerts = relationship("Alert", back_populates="incident", cascade="all, delete-orphan", lazy="selectin")
    report = relationship("RootCauseReportModel", back_populates="incident", uselist=False, cascade="all, delete-orphan", lazy="selectin")

    def to_dict(self) -> dict[str, Any]:
        """Convert model representation to a dictionary."""
        return {
            "id": self.id,
            "service_id": self.service_id,
            "status": self.status,
            "created_at": self.created_at.isoformat(),
            "updated_at": self.updated_at.isoformat(),
            "alerts": [alert.to_dict() for alert in self.alerts],
            "report": self.report.to_dict() if self.report else None,
        }


class Alert(Base):
    """Represents an individual alert payload received via webhooks."""

    __tablename__ = "alerts"

    id = Column(String(36), primary_key=True, default=generate_uuid)
    incident_id = Column(String(36), ForeignKey("incidents.id", ondelete="CASCADE"), nullable=False, index=True)
    alert_message = Column(String(1000), nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)

    # Relationships
    incident = relationship("Incident", back_populates="alerts")

    def to_dict(self) -> dict[str, Any]:
        """Convert alert fields to a dictionary."""
        return {
            "id": self.id,
            "incident_id": self.incident_id,
            "alert_message": self.alert_message,
            "created_at": self.created_at.isoformat(),
        }


class RootCauseReportModel(Base):
    """Represents a persisted RootCauseReport generated by the orchestrator LLM."""

    __tablename__ = "root_cause_reports"

    id = Column(String(36), primary_key=True, default=generate_uuid)
    incident_id = Column(String(36), ForeignKey("incidents.id", ondelete="CASCADE"), unique=True, nullable=False, index=True)
    root_cause = Column(String(2000), nullable=False)
    evidence_summary = Column(String(4000), nullable=False)
    affected_services = Column(JSON, nullable=False)  # List of service IDs
    remediation_steps = Column(JSON, nullable=False)  # List of strings
    confidence_score = Column(Float, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)

    # Relationships
    incident = relationship("Incident", back_populates="report")

    def to_dict(self) -> dict[str, Any]:
        """Convert report fields to a dictionary."""
        return {
            "id": self.id,
            "incident_id": self.incident_id,
            "root_cause": self.root_cause,
            "evidence_summary": self.evidence_summary,
            "affected_services": self.affected_services,
            "remediation_steps": self.remediation_steps,
            "confidence_score": self.confidence_score,
            "created_at": self.created_at.isoformat(),
        }
