"""add_service_registry_and_kg_proposals_tables

Revision ID: 4cc7b3153ded
Revises: d2b6ecda76b9
Create Date: 2026-07-20 20:50:55.442139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cc7b3153ded'
down_revision: Union[str, Sequence[str], None] = 'd2b6ecda76b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kg_change_proposals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('service_id', sa.String(length=100), nullable=False),
    sa.Column('commit_sha', sa.String(length=64), nullable=False),
    sa.Column('repo', sa.String(length=255), nullable=False),
    sa.Column('architecture_type', sa.String(length=50), nullable=False),
    sa.Column('component_id', sa.String(length=200), nullable=False),
    sa.Column('proposed_changes', sa.JSON(), nullable=False),
    sa.Column('diff_summary', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('admin_feedback', sa.Text(), nullable=True),
    sa.Column('parent_proposal_id', sa.String(length=36), nullable=True),
    sa.Column('reviewed_by', sa.String(length=255), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_proposal_id'], ['kg_change_proposals.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kg_change_proposals_service_id'), 'kg_change_proposals', ['service_id'], unique=False)
    op.create_index(op.f('ix_kg_change_proposals_status'), 'kg_change_proposals', ['status'], unique=False)
    op.create_table('service_registry',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('service_id', sa.String(length=100), nullable=False),
    sa.Column('repo', sa.String(length=255), nullable=False),
    sa.Column('architecture_type', sa.String(length=50), nullable=False),
    sa.Column('owner_team', sa.String(length=100), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('alert_threshold', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_registry_service_id'), 'service_registry', ['service_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_registry_service_id'), table_name='service_registry')
    op.drop_table('service_registry')
    op.drop_index(op.f('ix_kg_change_proposals_status'), table_name='kg_change_proposals')
    op.drop_index(op.f('ix_kg_change_proposals_service_id'), table_name='kg_change_proposals')
    op.drop_table('kg_change_proposals')
    # ### end Alembic commands ###
