"""add uncertainty and model_used to root_cause_reports

Revision ID: 8312e5affb53
Revises: 4cc7b3153ded
Create Date: 2026-07-22 22:26:43.271158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8312e5affb53'
down_revision: Union[str, Sequence[str], None] = '4cc7b3153ded'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('root_cause_reports', sa.Column('uncertainty', sa.String(length=2000), nullable=False, server_default=""))
    op.add_column('root_cause_reports', sa.Column('model_used', sa.String(length=100), nullable=False, server_default=""))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('root_cause_reports', 'model_used')
    op.drop_column('root_cause_reports', 'uncertainty')
    # ### end Alembic commands ###
