"""add_incident_knowledge_and_resolution_tables

Revision ID: d2b6ecda76b9
Revises: 0cc07c67291a
Create Date: 2026-07-17 16:13:35.471867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2b6ecda76b9'
down_revision: Union[str, Sequence[str], None] = '0cc07c67291a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident_knowledges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('applies_to_services', sa.JSON(), nullable=False),
    sa.Column('applies_to_error_types', sa.JSON(), nullable=False),
    sa.Column('symptoms', sa.Text(), nullable=False),
    sa.Column('root_cause_pattern', sa.Text(), nullable=False),
    sa.Column('immediate_steps', sa.Text(), nullable=False),
    sa.Column('permanent_fix', sa.Text(), nullable=False),
    sa.Column('escalate_if', sa.Text(), nullable=False),
    sa.Column('owner_team', sa.String(length=100), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incident_resolutions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('incident_id', sa.String(length=36), nullable=False),
    sa.Column('resolved_by', sa.String(length=36), nullable=False),
    sa.Column('what_was_root_cause', sa.Text(), nullable=False),
    sa.Column('what_fixed_it', sa.Text(), nullable=False),
    sa.Column('time_to_resolve_min', sa.Integer(), nullable=False),
    sa.Column('should_update_incident_knowledge', sa.Boolean(), nullable=False),
    sa.Column('incident_knowledge_id', sa.String(length=36), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['incident_knowledge_id'], ['incident_knowledges.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_resolutions_incident_id'), 'incident_resolutions', ['incident_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incident_resolutions_incident_id'), table_name='incident_resolutions')
    op.drop_table('incident_resolutions')
    op.drop_table('incident_knowledges')
    # ### end Alembic commands ###
